### ISSUE TITLE
TypeError: Cannot read property 'Properties' of undefined

### ISSUE THREAD

**Issue by debttestbot** [svdgraaf/serverless-fargate-tasks#2]
I just tried using this plugin from the examples in the README:

```
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           9.5.0
     Serverless Version:     1.38.0
```

serverless-fargate-tasks version: 0.1.0

`serverless.yml`:

```
service: serverless-test

plugins:
  - serverless-fargate-tasks

custom:
  fargate:
    network:
      public-ip: DISABLED
      subnets:
        - subnet-00
        - subnet-01
    tasks:
      my-task:
        image: alpine:3.8

provider:
  name: aws
  stage: dev
  region: us-east-1
```

Error:

```
Fargate Tasks Plugin
Processing my-task

  Type Error ---------------------------------------------

  Cannot read property 'Properties' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'Properties' of undefined
    at Object.keys.forEach.identifier (/Users/bgibbs/secops/git_python/node_modules/serverless-fargate-tasks/lib/index.js:54:54)
    at Array.forEach (<anonymous>)
    at ServerlessFargateTasks.compileTasks (/Users/bgibbs/secops/git_python/node_modules/serverless-fargate-tasks/lib/index.js:37:32)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55)
```

I'm fairly new to working with the serverless framework, so I'm hoping that I'm just missing a config option somewhere?
