### ISSUE TITLE
Ability to customize task name

### ISSUE THREAD

**Issue by ChristopheBougere** [svdgraaf/serverless-fargate-tasks#4]
Thanks for this plugin @svdgraaf, manually setting up a fargate cluster is quite cumbersome!
Right now the task name is the key of the object, which prevents using variables in it.
In my case, I'd like to have the stage in the task name, so I can deploy my service in different stages on the same AWS account.
Having the ability to override the name in a property would be great, something like this:
```yaml
custom:
  fargate:
    network:
      subnets:
        - subnet-1234
        - subnet-5678
    tasks:
      my-task:
        name: my-task-${self:provider.stage}
        image: 123456789369.dkr.ecr.eu-west-1.amazonaws.com/my-image
```
